name: deepspot

channels:
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - numpy
  - pandas
  - scipy
  - anndata
  - scanpy
  - squidpy
  - matplotlib
  - pyvips
  - scikit-learn
  - igraph

  - pip:
      - torch
      - torchvision
      - torchaudio
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - lightning
      - plotnine
      - ipykernel
      - huggingface_hub
      - transformers
      - timm
      - scikit-misc
      - openslide-python
